# Generated by Django 2.2.24 on 2021-06-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdigitGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnumber',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
