# Generated by Django 2.2.24 on 2021-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdigitGame', '0002_newnumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField()),
            ],
        ),
    ]
